services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - spark_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spark_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - spark_network

  spark-master:
    image: bitnami/spark:3.5.0
    container_name: spark_master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7070
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master --port 7070 --webui-port 8080
    ports:
      - "7070:7070"
      - "8080:8080"
    networks:
      - spark_network

  spark-worker-1:
    image: bitnami/spark:3.5.0
    container_name: spark_worker_1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7070
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7070 --webui-port 8081
    depends_on:
      - spark-master
    networks:
      - spark_network

  spark-worker-2:
    image: bitnami/spark:3.5.0
    container_name: spark_worker_2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7070
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7070 --webui-port 8081
    depends_on:
      - spark-master
    networks:
      - spark_network

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./jupyter_code:/home/jovyan/code
    depends_on:
      - spark-master
      - mongodb
    networks:
      - spark_network

  python-app:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python_app
    depends_on:
      - kafka
      - mongodb
    volumes:
      - ./jupyter_code:/app
    networks:
      - spark_network

networks:
  spark_network:
    driver: bridge

volumes:
  mongodb_data: